# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 打包发布到Releases

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # 允许手动触发该工作流
  
jobs:
  build:
    name: 打包工作
    runs-on: ubuntu-latest

    steps:
      - name: 克隆代码
        uses: actions/checkout@v4
        with:
          ref: main # 指定主分支

      - name: 指定Node.js版本
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: 使用当前时间设置 VERSION
        run: |
          echo "VERSION=v$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: 安装依赖
        run: npm install

      - name: 打包
        run: node build.js -v ${{ env.VERSION }}

      - name: 创建谷歌浏览器扩展zip文件
        run: zip -r ./dist.zip ./dist

      - name: 创建Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: ./dist.zip

      - name: 推送dist到另一个分支
        run: |          
          cd dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b pages
          git add .
          git commit -m "自动部署: 来自 ${{ github.repository }} 的构建产物 ${{ env.VERSION }}"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git pages
